Algoritmo "Revisão23"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/09/2024
Var
// Seção de Declarações das variáveis
i:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("O quadrado de números de 1 a 20")
para i de 1 ate 20 faca
escreval(i,"² = ",i^2)
fimpara







Fimalgoritmo