Algoritmo "10_repita"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/08/2024
Var
// Seção de Declarações das variáveis 
contadora:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
contadora <- 1
repita
escreval (contadora,", ")
contadora <- contadora + 1
ate contadora > 10


Fimalgoritmo