Algoritmo "vetor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/09/2024
Var
// Seção de Declarações das variáveis 
vet: vetor [1..10] de real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
vet[2]<- 256,65

Fimalgoritmo