Algoritmo "matriz"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/09/2024
Var
// Seção de Declarações das variáveis 
tabela: vetor [0..4,0..6] de caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 tabela[1,4] <- "oi"
 //tabela[1][4]
Fimalgoritmo